services:
  db:
    image: postgres:15
    container_name: zaxbox-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zaxbox
      POSTGRES_PASSWORD: zaxbox.net@2025
      POSTGRES_DB: zaxboxdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
