const privacyPolicy = () => {
  return (
    <>
    <div className=" flex justify-center items-center text-center">
      <h1 className='text-4xl'>Privacy Policy</h1>
    </div>
    
    <div className=" border border-[#d3b46650] mt-5"></div>
    <div className="py-8 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div className="space-y-6">
        {/* Introduction */}
        <div className="prose max-w-none">
        <span className="font-bold">Policy between ZAXBOX TRADING SERVICES (hereinafter referred to as ZAXBOX) and you, constitutes our commitment to your privacy on our website, apps, social media platforms, administrative records and premises.</span>
        <br /> <br />








        <div className="prose max-w-none">
            <h4 className="text-xl font-semibold text-gray-900 mb-2">1.0 Introduction</h4>
            <p className="">
              We at zaxbox respect privacy and protect the interest of our visitors. Please take a moment to read this privacy 
              policy carefully as we are only responsible for the terms stated in this document. If you have any questions about 
              this policy, please submit your queries via our support channels.
            </p>
            
            <h5 className="text-lg font-medium text-gray-800 mt-6 mb-1">1.1 Modification</h5>
            <p className="">
              Our privacy policy is subject to modification from time to time because of the need to update our users/visitors 
              to modern realizations of incorporation of their data. To this end, an email will be sent to you earlier, provided 
              you are a registered user, via the email address specified in your account. This is to serve as means of notice to 
              our esteemed users prior to when material changes will take effect, or as otherwise required by the law.
              Effective date of material changes will be indicated at the top of this page.
            </p>
          </div>
          
          {/* Acceptance of Privacy Policy */}
          <div className="mt-8">
            <h4 className="text-xl font-semibold text-gray-900 mb-2">2.0 Acceptance of Privacy Policy</h4>
            <p className="">
              Using and accessing our services indicates that you agree to the terms of this Privacy policy. Where required, 
              we will seek your consent to collect any form of data generated by your usage of our services or provided directly 
              by you in response to our tasks and/or criteria. We will notify users of actions carried out which might include 
              collection, use and disclosure of personal information to third-parties which we operate with.
            </p>
            <p className=" mt-4">
              More so, just-in-time disclosure of information about data processing of your personal information is very sacrosanct 
              to us. If you do not agree with our Privacy policy or feel abridged by any aspect of this Privacy policy, please 
              discontinue use of our services immediately.
            </p>
          </div>
          
          {/* Personal Information Collection */}
          <div className="mt-8">
            <h4 className="text-xl font-semibold text-gray-900 mb-2">3.0 The Personal Information we Collect</h4>
            <p className="">
              Personal information is basically data that identifies an individual or data identifiable to a person. However, 
              the definition of personal information is subject to applicable law in your physical location. The personal 
              information we use includes:
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 ">
              <li>Information you provide to us.</li>
              <li>Information collected automatically and.</li>
              <li>Information gotten from our affiliates and third parties.</li>
            </ul>
            
            <h5 className="text-lg font-medium text-gray-800 mt-6 mb-1">3.1 Information provided to us:</h5>
            <p className="">
              This category includes data you consciously provide when asked to. They are the basic identity-enabling data that 
              help us categorize our users. There are subdivisions which include:
            </p>
            
            <p className="font-medium mt-4 mb-2">Personal Informations</p>
            <ul className="list-disc pl-5 space-y-1 ">
              <li>Full name.</li>
              <li>Date of birth.</li>
              <li>Nationality.</li>
              <li>Gender.</li>
              <li>Age restriction.</li>
              <li>Phone number.</li>
              <li>Home address.</li>
              <li>Email address.</li>
            </ul>
            
            <p className="font-medium mt-4 mb-2">Formal Identification Information</p>
            <p className="">
              Government issued ID document e.g passport, driver's licence, national identity card details, tax ID number and 
              others in this category in combination with the requirements of the law under financial anti-money laundering laws.
            </p>
            
            <p className="font-medium mt-4 mb-2">Financial information</p>
            <p className="">
              Bank account, transaction history, trading data and/or tax information may be required of you.
            </p>
          </div>
          
          {/* More sections of privacy policy... */}
          <div className="mt-8">
            <h5 className="text-lg font-medium text-gray-800 mb-1">3.2 Information collected automatically:</h5>
            <p className="">
              These are retrieved under applicable law. They include more complex data (somewhat back-end) about your activities 
              relating with us that we collect. They contain all interaction with the sites or use of services. This category of 
              information helps us address customer support issues, improve the performance of our sites and services, streamline 
              services to fit, protect you from hacks and fraudulent actions by detection of unauthorized access.
            </p>
            
            <p className="font-medium mt-4 mb-2">Online Identifiers:</p>
            <p className="">
              Geographical location/tracking details, browser fingerprint operation system, browser name and version and/or 
              personal IP addresses.
            </p>
          </div>
          
          {/* Contact Section */}
          <div className="mt-8 border-t pt-6 border-gray-200">
            <h4 className="text-xl font-semibold text-gray-900 mb-2">6.0 How You Can Contact Us</h4>
            <p className="">
              If you have any concerns about our privacy policy or have any issues with our services you want resolved, 
              send us a message email via: <a className=" underline text-[#D3B466]" href="mailto:hi@zaxbox.com">hi@zaxbox.com</a>
            </p>
            
            <h4 className="text-xl font-semibold text-gray-900 mt-6 mb-2">Cookie Policy</h4>
            <p className="">
              Cookies are small files placed on your computer's hard drive that enables the website to identify your computer 
              as you view different pages. Cookies allow websites and applications to store your preferences in order to present 
              contents, options or functions that are specific to you. Like most interactive websites, our website uses cookies 
              to enable the tracking of your activity for the duration of a session. Our website uses only encrypted session 
              cookies which are erased either after a predefined timeout period or once the user logs out of the platform and 
              closes the browser. Session cookies do not collect information from the user's computer. They will typically store 
              information in the form of a session identification that does not personally identify the user.
            </p>
          </div>
        


          </div>
    </div>
    </div>

    
    </>
  );
}


export default privacyPolicy;